export default {
    GET_LOGS: 'GET_LOGS',
    SET_LOADING: 'SET_LOADING',
    SET_LOGERROR: 'SET_LOGERROR',
    ADD_LOG: 'ADD_LOG',
    DELETE_LOG: 'DELETE_LOG',
    UPDATE_LOG: 'UPDATE_LOG',
    SET_CURRENT: 'SET_CURRENT',
    CLEAR_CURRENT: 'CLEAR_CURRENT',
    SEARCH_LOG: 'SEARCH_LOG'
}